### ISSUE TITLE
Association Abort Error

### ISSUE THREAD

**Issue by accacc** [SaravananSubramanian/dicomdotnet#1]
Hello,

I have installed an orthanc server on my local computer, when I try to establish a connection using your library I get the following error? Do you have any idea?

Association Abort [source: ServiceUser; reason: NotSpecified]

**Comment by SaravananSubramanian** [comment]
This could happen for a variety of reasons including possibly not registering your app's AE information with Orthanc. The server may not fully disclose why it aborts a connection for security reasons. I would also use DICOM diagnostic tools (some are specified in my DICOM tutorials) as well. More than anything, I would refer to the Orthanc Server FAQ pages for diagnosing error messages. This will be first place to start. Thank you!
